### PR TITLE
Expand C-API doc comments re warnings

### PR DESCRIPTION
**Pull request by m-holger**
@jberkenbilt ,

- is my understanding correct?
- would it make sense to include this in qpdf-c.h?
- would it make sense to handle the exceptions in qpdf_get_trailer and qpdf_get_root?

Thanks

### CODE REVIEW

**Comment by jberkenbilt** [comment]
The information is not entirely accurate, but I'd have to study the code to remember all the details. In particular, warnings can be generated in a lot of different ways, most of which are because of issues in the PDF itself. qpdf_get_trailer and qpdf_get_root should be like other functions in that they should translate exceptions into error codes that can be handled by C code. I'll respond to your other questions on the other PR.

In general, I support updating the documentation in any way that helps with understanding. In my professional life, I'm always telling people the write the documentation they want to read. In other words, if you try to figure something out and the documentation is inadequate, update the documentation once you have gained understanding. I am happy to review and accept such contributions, though it will take me some time to assess their accuracy as I haven't looked at this part of the code for a long time.

**Comment by m-holger** [comment]
> The information is not entirely accurate, but I'd have to study the code to remember all the details. In particular, warnings can be generated in a lot of different ways, most of which are because of issues in the PDF itself. 

I was afraid of that. I am happy to investigate further. I assume that the only way a warning can be generated is by some call to QPDF::warn.

> qpdf_get_trailer and qpdf_get_root should be like other functions in that they should translate exceptions into error codes that can be handled by C code.

Do you want me to have a stab at that?

**Comment by jberkenbilt** [comment]
> I was afraid of that. I am happy to investigate further. I assume that the only way a warning can be generated is by some call to QPDF::warn.

Yes, QPDF::warn is the path. I wouldn't enumerate it too much though -- the comment will become stale. I or someone else could add another warning case and fail to update the comment. I don't know why you need to list the specific cases that cause warnings. It would be more helpful to point out correct ways to use the library if they are missing. For example, mentioning that passing an invalid object handle generates a warning is fine, but claiming that there are only two distinct ways to get a warning isn't fine even if it happens to be true at the moment. A comment explaining that any warnings generated by the qpdf library are preserved and that the C API generates a few additional one is fine. You can make it a little more specific if you want.

> Do you want me to have a stab at that?

Sure. It looks like I added those more recently and forgot about `trap_errors`, so that's definitely a bug for which a fix would be welcome. If you can't get it to work, just open an issue, and I'll make sure it gets fixed in the next update. I have added a note in README-maintainer (on my work branch, not merged yet) so I don't make that mistake again.

**Comment by m-holger** [comment]
>  I don't know why you need to list the specific cases that cause warnings

I don't really. What I was hoping is that once

1. I call a function returning a qpdf_oh
2. the function returns a handle to a non-Null object,
3. and qpdf_oh_get_type_code(to be written) returns a valid type code

I can call all methods applicable to the type without  worrying about warnings( until I receive a Null object).

If I cannot rely on that, I will need to check for warnings on every call to the C-API

**Comment by m-holger** [comment]
I guess the flip side to the question is:

- Are there circumstances where a function call produces a warning and also valid data?
- How do I distinguish between a Null object representing a failed function call and a Null object that is actually part of the pdf file (and is there a need to distinguish between the two?)?

**Comment by jberkenbilt** [comment]
I think handling warnings on a per-call basis is going to be a dead-end path. There's not necessarily any kind of correlation between warnings and null objects. There is no way to tell the difference between a null object that is in the file and one that is returned from a warning. Basically qpdf gives warnings when something in the PDF is out of spec. It takes its best guess about what to do and issues a warning to let the user know that something might not be right. It's really no different from what all the PDF readers do, except qpdf tells you about it and almost everything else just tries to resolve issues silently. The fact is that the PDF spec is arcane, and for most people who write PDF, their validation strategy is "it's valid if acrobat can read it." Usually qpdf will produce valid data on slightly damaged files that it creates warnings about because qpdf has been around for a long time and has had lots of time for its recovery code to get mature of handling millions (literally) of erroneous files. Trying to capture and handle warnings is essentially trying to duplicate logic that has been built off of years of empirical evidence while developing qpdf.

With the exception of the cases you already identified by looking at the code, warnings are indications of damage in the PDF file that your code (or mine) can't do anything about without taking a guess. The best you can do is ignore them, pass them along to the user, or have a human study them for deeper analysis. When qpdf is able to unambiguously deal with something that is out of spec, it just does so. When it is taking a guess that may or may not be right, it issues a warning. If you find a case where qpdf issues a warning and generates invalid data, it's worth reporting it as a bug. Sometimes there's something I can do internally to improve the recovery code. Other times, there isn't. The number of cases that qpdf has issued a warning because it is making a mistake in interpreting the file is very small -- probably fewer than 10 bugs of that type in the life of the software, and generally then it is on a newly added feature.

**Comment by m-holger** [comment]
I agree where warnings are of the nature you describe. My concern is about QPDFObjectHandle::typeWarning kind of warnings, which indicate user error (incorrect use of the C-API), such as in 

```rust

    let root  = pdf.root();
    println!("warning {:?}", pdf.next_warning());
    let i = root.int_value_as_int();
    println!("i = {:?}", i);
    println!("error {:?}", pdf.error());
    println!("warning {:?}", pdf.next_warning());
```
which produces 
```
handle in root 6
warning None
WARNING: ./test.pdf object stream 1433, object 1475 0 at offset 7605: operation for integer attempted on object of type dictionary: returning 0
i = 0
error None
warning Some(Pdf { code: 5, full_text: "./test.pdf object stream 1433, object 1475 0 at offset 7605: operation for integer attempted on object of type dictionary: returning 0" })
```
In that situation I would feel much more comfortable to return some Error or at least None rather than 0 or Some(0).

I'll need to think about this a bit more

**Comment by jberkenbilt** [comment]
If you want to avoid those errors, just do explicit type checks. In other words, check is_dictionary before calling dictionary methods. I try to do this throughout the library, but there are cases where I have forgotten. There is, unfortunately, no way to know at compile time because QPDFObjectHandle is untyped in that sense. This is not really possible to get around because it is often the case in PDF itself that a particular dictionary may have a key whose value can be of different types, and even if that were not the case, there are lots of files in the wild that do it. I know it's uncomfortable for those of us who like strong typing, but PDF is just not strongly typed. So you can avoid the warnings in your own code by always checking the type before you call a method, but I can't guarantee that the library won't occasionally generate that warning. In older versions of qpdf, this is used to be an error, but making it a warning has vastly increased the number of erroneous PDF files that qpdf can handle.

If you find any real PDF files where qpdf generates a warning of the type you describe, I would consider it a bug.

I guess a good way to put it is that qpdf warnings, rather than giving an error, if the developer makes a mistake on the type, but in the absence of strong typing that simply isn't there for PDF, the alternative would be that people would write code that would crash all the time on bad files even if all compiler-time checks passed.

If I were doing it all over again and using a language like rust, I might create more strongly typed QPDFObjects or at least have an interface where you have to do a type assertion of some point before calling an accessor. Unfortunately, this is so deeply a part of the QPDF API that changing it would break just about all code that uses qpdf.

I'm very sympathetic to what you're struggling with here, and I do understand the issue fully. It's just that, for better or worse, the QPDF API behaves the way it does, and PDF files are full of type inconsistencies, sometimes by design, and sometimes by happenstance.

**Comment by jberkenbilt** [comment]
I suppose if one were going to go as far as writing an official rust API for qpdf, one could get rid of all the accessor/mutator methods on the untyped object and force narrowing of some sort. I feel like `Option` in rust presents a pattern for this style. Yes, sometimes it's hard having an old code base with old decisions that are too hard to change....

**Comment by jberkenbilt** [comment]
Last little comment: I went through a stage in my career where I got excited about dynamically typed languages like Python, but I have come around to much more strongly preferring strict static typing, and I think the industry is moving in that direction. Take, for example, the rising popularity of typescript over plain javascript, ruby 3.0 adding strict typing, advisory type assertions in Python, even languages like dart having static typing.

**Comment by m-holger** [comment]
I share you feelings re strict typing. In my days I favoured Modula-2 over C and Fortran 77 (or god forbid Fortran IV). I prefer my compiler rather than my users to pick up my programming errors. I am also a fan of exceptions, especially if they crash my programs every time. I certainly prefer them to rare, difficult to reproduce crashes and obscure errors.

From the perspective of calling the C-API I can live with the way warnings / invalid function call are handled. That said, I think something like the Rust `Option` pattern could be implemented without breaking the existing API by making `qpdf_oh`s typed. See 2nd commit for a possible approach.

**Comment by jberkenbilt** [comment]
You've got me thinking about adding a safe mode API. I may well add this, but would definitely not do it in the way you've proposed. Instead, I would build it into the C++ API and then have a safe mode in the C API be implemented to use the newer C++ API. Something like this, with names still TBD:

In the old way, this is what you're supposed to do:
```
QPDFObjectHandle oh = getObjectFromSomewhere();
if (oh.isDictionary()) {
  QPDFObjectHandle value = oh.getKey("/Key");
}
```

but the API doesn't force you to do it, and you are free to do this instead:

```
QPDFObjectHandle oh = getObjectFromSomewhere();
QPDFObjectHandle value = oh.getKey("/Key");
```

In the second case, you get the warning if `oh` is not a dictionary, and value is the null object, which is a valid object, not a null pointer, but not what you probably expected. But it would be the same if the dictionary just didn't have `"/Key"` in it.

The new API would be like rust's Option in that it would make it harder for you to carelessly treat a non-dictionary as a dictionary. Here are some ideas:

```
QPDFSafeObjectHandle soh = getObjectFromSomewhere();

// QPDFSafeObjectHandle would be just like QPDFObjectHandle except
// none of the type-specific methods would be there.
QPDFDictionaryHandle dh = soh.asDictionary();
if (dh.isValid()) {
  QPDFSafeObjectHandle value = dh.value().getKey("/Key");
}
```

I could even go as far as making it a local error if you fail to call `isValid()` before calling `value()` so that you couldn't accidentally write code that fails to check.

For that matter, I could have a "safe mode" in `QPDFObjectHandle` that simply disallows calling any type-specific method without checking first. The problem is that there's now way to turn it on safely that would allow mixing safe and unsafe code.

Here's a possible compromise. `QPDFSafeObjectHandle` would be exactly like `QPDFObjectHandle` except that it would throw a `std::logic_error` if you called any type-specific method without first verifying the type. That would make it a little more like typescrypt than rust, but the idea would be the same -- you wouldn't be able to write code that just got lucky. It would force you to check even for valid cases. So if you did this:

```
QPDFSafeObjectHandle soh = getObjectFromSomewhere();
QPDFSafeObjectHandle value = soh.getKey("/Key");
```

this would raise `std::logic_error` even if soh was a dictionary. But this would work:

```
QPDFSafeObjectHandle soh = getObjectFromSomewhere();
if (soh.isDictionary()) {
  QPDFSafeObjectHandle value = soh.getKey("/Key");
}
```

because `QPDFSafeObjectHandle` would internally keep track of whether the type had been confirmed to be a dictionary. Migrating existing code to use this safe version would just be a matter of changing all occurrences of `QPDFObjectHandle` to `QPDFSafeObjectHandle` and making sure you had test coverage on every accessor/mutator method call. If you did and the code worked for the happy path, then you would be assured of never getting a warning about the a method called on an object of the wrong type.

I'd have to put some thought into the exactly API for this that would avoid duplication of code inside the library, not incur a significant performance hit, and still allow a convenient way of getting the current behavior on purpose but without the warnings. One test of a clean API would be that it would be possible for the C API to have minimal changes to use the new safe C++ API. I would also internally change all of QPDF's own QPDFObjectHandle objects to QPDFSafeObjectHandle, which should eliminate all these warnings from ever happening from library code.

What do you think?

**Comment by jberkenbilt** [comment]
P.S. I was a big fan of Modula 3 in the day. Regarding exceptions, I don't like them. They are non-local goto on steroids. Though more verbose, I prefer the rust style of error handling using the `Result` type. The idomatic golang solution of having methods return `(value, error)` is also good. It's easy to know whether or not all conditions are covered in both of these approaches. With exceptions, when you read and write code, you effectively have to keep in mind that flow could jump out of wherever you are to some arbitrary point in the stackframe at any time, and even if you do an exhaustive analysis, it could completely change without your notice. If you want to be lazy (for prototype code, experimentation, or whatever), you can still always use `unwrap()` in rust or `value, _ = whatever()` in go, and both go and rust have panic methods, but those are both cleaner than exceptions because you are explicitly ignore error conditions in the code.

I think I like exceptions in my Python code where I am writing smaller, simpler code that you can understand all of in one sitting, but for anything to big to have fully in your head, I'd rather use a language that requires explicit error handling. Both rust and go have good error wrapping, and rust as `?`.

**Comment by m-holger** [comment]
> Regarding exceptions, I don't like them. They are non-local goto on steroids.  Though more verbose, I prefer the rust style of error handling using the Result type.

I don't disagree. I too prefer the rust style of error handling. When I say that I am a fan of exceptions I mean unchecked exceptions/ Rust panics. To put it another way, I am not a fan of simply returning some default value in response to an uncorrectable error condition.

While not a fan of Python exceptions, I do like their approach of "do and ask forgiveness if necessary" instead of "check and do". So, to me 

```
QPDFSafeObjectHandle soh = getObjectFromSomewhere();
QPDFSafeObjectHandle output = soh.getKey("/Key");
```

feels perfectly acceptable and in my mind does not even warrant a warning(even if oh is not a dictionary). However, for this to work properly the user has to be able to tell whether the result is `Some(output)` or `None`. Also, if `output == None`, 
```
output.some_other_method()
```
must raise an Error and cannot return a `Some(some_thing)`. So, to me this would be the place to raise an logic error (maybe - I  will come back to this)

#### Methods returning an object handle

In terms of the C-API this would not really change anything. `oh == 0` is effectively already defined as None, and for the `! qpdf_oh_valid_internal` case, I think the C-API already duplicates how the C++ code would handles a Null object.

For the C++ code, it seems to me that all that is really necessary is to add an attribute to the Null type to indicate whether an instance is a pdf Null or a None (plus obviously the coding for safe mode).

#### Methods returning a scalar

This would obviously require changes to the C-API as there is no way to encode `None`. I would expect something like
```
result = oh.get_int();
value = (result != None) && oh.unpack_as_int(result);
```
where call unpack with a `None` result or using incompatible `get`/`unpack` combinations would be an error.

For the C++ code, new safe functions could return a

**Comment by m-holger** [comment]
On further reflection, raising a logic error when a function is called with an error Null object may not be a good idea as it would make it difficult to support a fluent programming style, eg allowing a user to write
```rust
if let Some(subtype) = page.key("\Annotation").item(i).key("\Subtype").name_value() {
   // ...
}
```

**Comment by m-holger** [comment]
Is my redraft ok?

**Comment by jberkenbilt** [comment]
I haven't read anything here, but I will take the time to do so. I think your redraft is correct, but there are two issues:
* Your description of the behavior is not specific to the C API. I'd rather have these comments be in QPDFObjectHandle with a reference to them in qpdf-c.h, or if it really helps to have it in both places, then I would put in both places with each referring to the other. It might be more efficient if I fix up the documentation and credit you the language and suggestions.
* This discussion has made me wonder whether the behavior is correct/desirable. I still have to read over everything, but I can tell you these things are part of my thinking:
  * There will be no "attributes" or anything like that attached to object handles. I am not going to add any way in the library to be able to tell the difference between a null (or other object) that was returned as a fallback vs. one that wasn't. This would greatly complicate the code. Think about all the cases around copying objects around, etc. Also, you can't attach attribute to things returned by getIntValue, etc. It would be a significant departure from this aspect of QPDF's API, which has been stable since the first release.
  * I'm having doubts about whether these conditions should be creating warnings at all, since these are not situations the user can do anything about. I can't make them be errors again (as they once were) because that will cause qpdf to reject files it currently accepts (and that other readers accept). I'm leaning toward having the default behavior to be to return fallback values silently with one or two options for debugging: a global flag that would tell QPDF to generate warnings for this that could be enabled by developers who want to make sure their code is right, and/or a safe mode similar to what I was discussing earlier.

**Comment by jberkenbilt** [comment]
Hit return too early. I was going to continue:

There are really two distinct reasons for these type warnings: 1) something is actually wrong with the PDF file. There's nothing anyone can do about this other than the original creator, so there's little value in warning under circumstances other than when qpdf is being used as a PDF checker (which was actually its original reason for being); 2) programmer error: someone writes code that incorrectly interprets of the PDF spec, such as treating something always as an object of a certain type when it is supposed to be a different type. I have made these mistakes myself on several occasions, and the fact that QPDF warns for these cases has had two major benefits: it enables the software to otherwise work on those files even if it isn't perfect, and it has exposed the error so that someone can report it and I can fix it.

I have to balance all these considerations when thinking about what to do here.

I'm also not planning on adding functionality to the C API that goes beyond functionality in the C++ API, so anything we do to the C API to help with this case must be implemented in the main API and carried forward.

If we want to continue this discussion, we can create a "discussion" issue on the main qpdf repository rather than talking about here where the discussion will be lost. I think this is a valuable conversation that I would want to be able to refer back to myself in the future and that I would point others to who might come across similar issues.

**Comment by jberkenbilt** [comment]
Finally caught up on this. My thinking at this time is that, if I add a safe object handle API, I will make the unsafe version silently return fallback values without issuing warnings, but I'm not certain yet. I'd have to start working with it and seeing what impact it has an existing code. Your point about fluent interfaces is correct, and I actually have a plan in qpdf 11 to rework some APIs to make fluent interfaces possible. I want to be able to do
```
auto oh = dict.addKey("/Something", QPDFObjectHandle::newArray());
oh.appendItem(...);
```
but that would conflict with a fluent interface like
```
dict.addKey("/Something", QPDFObjectHandle::newArray()).addKey("/Else", ...);
```

With safe objects, maybe it would be possible to have something that still allows chaining, which I do all over the place. Anyway, this will require more thought. Let's end the discussion here and open a discussion issue if we want to continue.

One thing I can promise is that there isn't going to be a way to test based on the return value whether or not an object was a fallback value or an actual value. I'm just not willing to make that change. I don't think it's a real thing that people should be made to think about. It would be nice to make something equivalent to like javascript's a?.b?.c.

All that said, I'm kind of anti-magic, and I'm not willing to trade safety for brevity.

As you can probably tell by now, there's a lot of nuance and subtlety here. QPDF is 70k lines and 20 years old, and a lot of people have written code that uses it, so I have to be very careful and thoughtful about this type of change.

**Comment by jberkenbilt** [comment]
I've gone through some of the code and looked at it would it would take to create a safe QPDFObjectHandle. I have decided that it will be a great deal of work without a whole lot of benefit. However, I'm thinking that maybe the default behavior of the code should be to not warn about these type fallback return values. Instead, I was thinking I might have the behavior controlled by an environment variable, like perhaps QPDF_DEBUG, which could be set to something like a comma-separated list of strings. That way, it would still be possible to turn them on. Or maybe I could have them on by default and have a debugging setting for strict mode that make it easier for developers to check their code while they are developing.

I'm actually kind of reluctant to turn this off because it has been so useful in diagnosing problems with both broken PDF files and bugs in qpdf over the years. But having a flag I could turn on during development/testing that would log or fail whenever I do a dereference without a check could go a long way to tightening up the code, thereby perhaps eliminating these warnings from happening for a reason other than failure to check from user code.

I'm also wondering about the documentation....maybe it's time for a qpdf wiki?

Anyway, I'll stop commenting here. I'm happy to continue the discussion in a discussion issue off of the main qpdf repo.

**Comment by m-holger** [comment]
>  without a whole lot of benefit. 

I have come to suspect the same.

> maybe the default behavior of the code should be to not warn about these type fallback return values

I certainly feel that in many cases the warnings provide unnecessary clutter

> I was thinking I might have the behavior controlled by an environment variable, like perhaps QPDF_DEBUG

That may be a good idea, however, I don't think that this is the whole solution. My current thinking is that some warnings (e.g. those generated by `typeWarning`)  should be available to users of the C-API, and any switches controlling the treatment of warnings should should also be able to be controlled programmatically through the C-API. The more I look into it the more I get concerned re the treatment of errors and warnings in the C-API. I need to think about this further.

> ....maybe it's time for a qpdf wiki?

I was asking myself the same question - so yes please

>  It might be more efficient if I fix up the documentation 

No problem with that. The reason for my draft is to get confirmation of my (, as it turns out, mis-)understanding of the C-API and to indicate what I feel would be helpful documentation. Feel free to use or adapt any part of my draft.

> If we want to continue this discussion, we can create a "discussion" issue on the main qpdf repository rather than talking about here where the discussion will be lost.I think this is a valuable conversation that I would want to be able to refer back

I agree. That said, I find it helpful to bounce of ideas in private before committing them to public scrutiny. Also, certain questions are much easier to ask in private, such as 

> I am not going to add any way in the library to be able to tell the difference between a null (or other object) that was returned as a fallback

Does this not happen already, e.g. in `QPDFObjectHandle::getKey`, where " -> null returned from getting key " + key + " from non-Dictionary" is added to the `ObjectDescription`?

>  Anyway, I'll stop commenting here.

Would an acceptable compromise be to correct my misunderstandings here and answer any valid questions in the wiki / documentation?

**Comment by jberkenbilt** [comment]
> I certainly feel that in many cases the warnings provide unnecessary clutter
> 
> > I was thinking I might have the behavior controlled by an environment variable, like perhaps QPDF_DEBUG
> 
> That may be a good idea, however, I don't think that this is the whole solution. My current thinking is that some warnings (e.g. those generated by `typeWarning`) should be available to users of the C-API, and any switches controlling the treatment of warnings should should also be able to be controlled programmatically through the C-API. The more I look into it the more I get concerned re the treatment of errors and warnings in the C-API. I need to think about this further.
> 

I will be eager to hear your suggestions. All warnings are actually type `QPDFExc`, which already has an error code field. I think it would a great enhancement to just add a specific error code for type warnings. This would actually allow you to filter those out or use that to detect type warnings by checking warnings before and after like you suggested in one of your other comments. I think I should take a pass through every QPDFExc that's instantiated in the code and decide what error code they should have. I overuse "damaged PDF".

> > ....maybe it's time for a qpdf wiki?
> 
> I was asking myself the same question - so yes please
> 

Okay, I'll look at the github wiki feature. I'm concerned about wikis in general because they get outdated, but I'll give it some thought.

> > It might be more efficient if I fix up the documentation
> 
> No problem with that. The reason for my draft is to get confirmation of my (, as it turns out, mis-)understanding of the C-API and to indicate what I feel would be helpful documentation. Feel free to use or adapt any part of my draft.
> 

I will absolutely use your drafts as a starting point, and I will tag you so you can read what I come up with and make sure it meets your needs. The only way for me to know whether the documentation is helpful to people other than myself is to get feedback.

> > If we want to continue this discussion, we can create a "discussion" issue on the main qpdf repository rather than talking about here where the discussion will be lost.I think this is a valuable conversation that I would want to be able to refer back
> 
> I agree. That said, I find it helpful to bounce of ideas in private before committing them to public scrutiny. Also, certain questions are much easier to ask in private, such as

Actually, I'm happy to discuss anything in private that you want to discuss in private. I just want to make sure that discussions leading up to decisions about the code are captured in public view. Most people won't care though. I can always come back here and copy things into some suitable location as long as I do it soon. There are some users who only communicate with me by direct email. Then I have a full log of the conversation and can distill it into whatever type of notes I feel I need. Often this ends up being comments in code, which is actually the best place to record internal design rationale. I would much rather have the discussion in private than not have the discussion, and I am happy to defer to what is comfortable for you in thsi regard.

> 
> > I am not going to add any way in the library to be able to tell the difference between a null (or other object) that was returned as a fallback
> 
> Does this not happen already, e.g. in `QPDFObjectHandle::getKey`, where " -> null returned from getting key " + key + " from non-Dictionary" is added to the `ObjectDescription`?
> 

I suppose it does, but it's not reliable or robust to check things like the input source name or the exact text of the messages. While I do try to keep those things stable for the benefit of people who may be relying on them, they are not part of the API and are subject to change at my whim without regard to semantic versioning. That said, I think the error code idea I mentioned above will give you a reliable way to tell if you want, though it will not be by looking at the returned object.

> > Anyway, I'll stop commenting here.
> 
> Would an acceptable compromise be to correct my misunderstandings here and answer any valid questions in the wiki / documentation?

What I mean is that I will stop volunteering additional information here. I am happy to continue replying to your comments here. I'm also fine with switching this to a private email thread.

What I will do is to capture the flow of this discussion in a github discussion item which I will tag you on. I won't capture the dialog in a way that exposes your initial thoughts to public scrutiny but will instead describe where I've ended up along with the rationale and alternatives considered. I find it to be very valuable to capture that stuff because I know I won't remember it in the distant future. Then, as I come up with refinements during implementation, I will go there to update. You can feel free to comment there or here. I will reply either way. Of course, if I overlook something here, I may never notice because I won't come back here to look, so you might have to ping me. I'm pretty careful about my email though....

Anyway, I find it very useful/important to capture the thought process behind decisions. Often I will encounter a past decision in the future and think it's odd, sometimes mentally regressing to my original idea. If I see the discussion thread, then I can either say, "Oh yeah, that's why I did it that way," or "I see this basic assumption was wrong, so I'll change the decision." Both of those have happened. Most recently, I decided it was time to remove an internal pages cache. I spent a few hours refactoring code to avoid the cache, but ended up in a place where the new implementation had exactly the same complexity as the cache and was much less efficient. So I updated the comments in QPDF_pages.cc so my future self wouldn't do the same thing in a few years. This is completely like that -- it wouldn't surprise me at all if my future self once again decides that we need a safer version of QPDFObjectHandle, so capturing this discussion be helpful.

**Comment by jberkenbilt** [comment]
I have add this to my TODO file:

```
* Create a discussion issue and/or capture all the important details
  from https://github.com/m-holger/qpdf/pull/2, including carefully
  reviewing the suggested documentation changes to see what should be
  incorporated. Especially keep in mind the need for the C API to be a
  suitable starting point for understanding the library as people
  using qpdf from other than C++ will most likely start there.
```

This comment will might survive in the git history, but the specific reference to this PR will not remain anywhere visible for any length of time. I often rebase and filter out TODO edits as they create clutter in the history.

**Comment by m-holger** [comment]
> There are some users who only communicate with me by direct email. Then I have a full log of the conversation and can distill it into whatever type of notes I feel I need. 

I have no views re using github vs email. If it helps, I can use email for private discussions. Is it ejb@ql.org ?

> capture all the important details from https://github.com/m-holger/qpdf/pull/2,

I am in the process of putting together a more coherent note. You may wish to hold off and see whether it meets what you are looking for.

**Comment by jberkenbilt** [comment]
> I have no views re using github vs email. If it helps, I can use email for private discussions. Is it [ejb@ql.org](mailto:ejb@ql.org) ?

That will work. Please include `qpdf` somewhere in the subject. Then it will be tagged `qpdf` automatically in my email. It does help a little because it's easier for me to extract information from my own email than a conversation in someone else's fork.

> I am in the process of putting together a more coherent note. You may wish to hold off and see whether it meets what you are looking for.

Looking forward to it.

**Comment by jberkenbilt** [comment]
As I was updating the C API to be able to detect uninitialized objects, I realized what you meant about changing errors to warnings. It seems as though I designed the object handle API in a way that precludes the ability to handle errors as errors. Since those methods return values rather than error codes, I seem to have boxed myself into having to either store real error conditions, like accessing uninitialized objects, as warnings. I guess this is tolerable, but it's unfortunate. The alternative would be to have the api take pointers to the returned values, force you to register an error handler, or jump through some other hoop. I think we'll have to live with it the way it is, but I'll document it more clearly.

**Comment by jberkenbilt** [comment]
@m-holger I think I've captured everything from this thread in the latest changes, so I'm going to remove looking at it from my TODO file. If there's anything here that we haven't covered in some other place, feel free to draw it to my attention by email, through an issue, or whatever. :-)

**Pull request closed without merging**
